name: identificador_riesgos
description: "Verison 1.0"
publish_to: 'none'

version: 1.0.0+1

environment:
  # Ajustado para ser compatible con tu SDK 3.5.4
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  signature: ^5.0.0
  shared_preferences: ^2.3.0
  pdf: ^3.11.0

  # --- DEPENDENCIAS QUE FALTABAN AÑADIDAS ---
  printing: ^5.12.0      # Para la vista previa del PDF
  file_saver: ^0.3.1       # Para guardar el PDF (versión compatible)
  share_plus: ^10.1.0      # (Lo dejamos por si se usa en la rama web)
  # --- FIN DE LA ADICIÓN ---


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500